!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        01iEiV0A-User Interface:
          path: dataset/01iEiV0A-User Interface
          prefix: ncino
          standardFeature: false
          versions:
            05 April 2021:
              modifiedDate: '2021-12-23 14:22:17'
        01iEiV0A-Questionaire:
          path: dataset/01iEiV0A-Questionaire
          prefix: ncino
          standardFeature: false
          versions:
            Spring 2020 v3:
              modifiedDate: '2021-12-23 15:39:17'
        01xFqA04-Screen1:
          path: dataset/01xFqA04-Screen1
          prefix: eval1
          standardFeature: false
          versions:
            V1:
              modifiedDate: '2021-12-23 18:11:04'
